name: Deploy to Azure Web App - terry-property-tool
on:
 push:
   branches: [main]
 workflow_dispatch:

jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   environment:
     name: 'Production'
     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
   permissions:
     id-token: write

   steps:
   - uses: actions/checkout@v4
   
   - uses: actions/setup-python@v5
     with:
       python-version: '3.10'

   - run: pip install -r requirements.txt
       
   - run: zip release.zip ./* -r

   - uses: azure/login@v2
     with:
       client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_00FBAAD139FC459A9B25C088EA690C9D }}
       tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BAF33A4F4A34BA1830C2B7BB0961D61 }}
       subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_024331765DB3488798DD640935BC58B3 }}
       
   - uses: azure/webapps-deploy@v3
     id: deploy-to-webapp
     with:
       app-name: 'terry-property-tool'
       slot-name: 'Production'
